Milestone 2: User interface
rajkumardas2701/Tic-Tac-Toe pull request #2
Opened 2020-05-05 12:39 UTC by evansinho

## User_interface
####  this milestone we created:
- An interface that interacts with the user of the application.

2020-05-06 01:12 UTC, Anna-Myzukina commented
# Hi team! :clap: 
### Good job in Milestone 2 :eyes: 
### Just few changes before it can be approved :100: 

 [REQUIRED] game informs player if selected move is `invalid`

##### Implementation details

* [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [ ] Inside loop, you should all actions repeated for each move
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
![1](https://user-images.githubusercontent.com/26605804/81129449-05284380-8f4d-11ea-9a72-df285268b0b7.png)
* Using out-of-nowhere numbers to terminate a loop, for example `5.times do ... end` is a signal that something is wrong. Advise usage of terminating variable as above.

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"><img class="emoji" alt="computer" height="25" width="25" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"></g-emoji>

2020-05-06 06:32 UTC, evansinho commented
Hello, @Anna-Myzukina  thanks for the review.
but this changes you requested for are already there on the codebase. Kindly check properly again
Thanks.

2020-05-06 17:54 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x]  [REQUIRED] game displays board after player move
- [x] Lets include `lib` directory .
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-05-06 17:54 UTC, kobiyoyo commented on bin/main.rb
> +while board <= 9
The loop needs to be terminated with a variable,not a number

2020-05-06 18:25 UTC, evansinho commented
The board is displayed after a player move.

2020-05-07 13:06 UTC, rOluochKe requested changes
Hello @evansinho and @rajkumardas2701 
### You have done really well however, you have conflict you need to solve before another review.
![conflict](https://user-images.githubusercontent.com/8114528/81297825-8500fb80-907c-11ea-8f13-70488fb7c809.png)
- Solve the conflict and resubmit for another code review. Good luck
- Happy coding!

2020-05-07 15:42 UTC, rajkumardas2701 commented
Hi Raymond/Team,

We are awaiting approval/feedback before we can merge our user_interface branch to Development.
We will take care of conflict then :)

Thanks and Regards,
Rajkumar Das

2020-05-08 12:29 UTC, uryelah commented
Hello **Evanson Igiri & Rajkumar Das Das**, I'm Sarah, your last reviewer for this PR 👩‍🚀  

Good job fixing that conflict.

---------

## **Your capstone is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---------

**Keep being awesome devs and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-08 12:38 UTC, merged